# Generated by Django 4.0.6 on 2022-11-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('mobile_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=33)),
                ('group', models.CharField(choices=[('Volvo', 'Volvo'), ('Saab', 'Saab'), ('Flat', 'Flat'), ('Audi', 'Audi')], default='Volvo', max_length=6)),
                ('Price', models.IntegerField()),
                ('features', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=330)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=33)),
                ('lname', models.CharField(max_length=33)),
                ('addr', models.CharField(max_length=200)),
                ('birthdate', models.DateField()),
                ('tel', models.BigIntegerField()),
            ],
        ),
    ]
