# Generated by Django 4.0.6 on 2022-11-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=33)),
                ('category', models.CharField(max_length=33)),
                ('price', models.IntegerField()),
                ('features', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='tel',
            field=models.IntegerField(),
        ),
    ]
